package types

import (
	"errors"
)

var (
	// ErrWrongOutputFormatWithFieldExtractions ...
	ErrWrongOutputFormatWithFieldExtractions = errors.New("output format cannot be raw when using field extractions")
	// ErrOutputFormatRequiresExtractors ...
	ErrOutputFormatRequiresExtractors = errors.New("you cannot use this output format without either `extract` or `field_extractions`")
	// ErrMultipleExtractorsFound ...
	ErrMultipleExtractorsFound = errors.New("you can only specify either `extract` or `field_extractions`, not both")
	// ErrSourceGlobWithRawOutput ...
	ErrSourceGlobWithRawOutput = errors.New("source file cannot use globs when output type is not 'raw'")
	// ErrFormatGlobRequiresNoOutputFile ...
	ErrFormatGlobRequiresNoOutputFile = errors.New("source files of glob format cannot specify a `output_file` field for projection")
	// ErrUnsupportedSourceType ...
	ErrUnsupportedSourceType = errors.New("unsupported source type")
	// ErrOutputFileRequired ...
	ErrOutputFileRequired = errors.New("output_file field required for this projection type")
	// ErrUnsupportedSourceFormat ...
	ErrUnsupportedSourceFormat = errors.New("unsupported source format; must be file, glob, yaml, or json")
	// ErrUnsupportedOutputFormat ...
	ErrUnsupportedOutputFormat = errors.New("unsupported output format; must be one of raw, yaml, or json")
	// ErrAbsolutePathSource ...
	ErrAbsolutePathSource = errors.New("absolute paths for `source` are not permitted")
	// ErrUnableToInferSourceFormat ...
	ErrUnableToInferSourceFormat = errors.New("unable to infer source format, you should specify this explicitly")
	// ErrUnableToInferOutputFormat ...
	ErrUnableToInferOutputFormat = errors.New("unable to infer output format, you should specify this explicitly")

	// ErrMissingName ...
	ErrMissingName = errors.New("missing name field")
	// ErrMissingNamespace ...
	ErrMissingNamespace = errors.New("missing namespace field")
	// ErrBadName ...
	ErrBadName = errors.New("name field uses unsupported characters")
	// ErrBadNamespace ...
	ErrBadNamespace = errors.New("namespace field uses unsupported characters")
	// ErrInvalidName ...
	ErrInvalidName = errors.New("name must only consist of lower case alphanumeric characters, -, and . and be 253 chars or less")
	// ErrInvalidNamespace ...
	ErrInvalidNamespace = errors.New("namespace must only consist of lower case alphanumeric characters, -, and . and be 253 chars or less")
)
